import fs from "fs/promises";
import path from "path";
import { Prisma } from "@prisma/client";

type PdfInvoice = {
  invoiceNo: string;
  invoiceDate: Date;
  placeOfSupply?: string | null;
  gstin?: string | null;
  subtotal: Prisma.Decimal;
  taxableAmount: Prisma.Decimal;
  cgstTotal: Prisma.Decimal;
  sgstTotal: Prisma.Decimal;
  igstTotal: Prisma.Decimal;
  grandTotal: Prisma.Decimal;
  transaction: {
    transactionNo: string;
    store: {
      code: string;
      name: string;
      city?: string | null;
      state?: string | null;
      gstin?: string | null;
    };
    customer?: {
      name: string;
      phone?: string | null;
      email?: string | null;
      gstin?: string | null;
    } | null;
    items: Array<{
      quantity: number;
      unitPrice: Prisma.Decimal;
      taxableAmount: Prisma.Decimal;
      gstRate: Prisma.Decimal;
      cgstAmount: Prisma.Decimal;
      sgstAmount: Prisma.Decimal;
      igstAmount: Prisma.Decimal;
      lineTotal: Prisma.Decimal;
      product: {
        name: string;
        sku: string;
        hsnCode?: string | null;
      };
    }>;
  };
  payments: Array<{
    method: string;
    amount: Prisma.Decimal;
    paidAt?: Date | null;
    referenceNo?: string | null;
  }>;
};

const pdfEscape = (value: string) =>
  value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const formatMoney = (value: Prisma.Decimal) => value.toFixed(2);

const formatDate = (date: Date) =>
  new Intl.DateTimeFormat("en-IN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);

const buildPdf = (lines: string[]) => {
  const text = lines
    .slice(0, 52)
    .map((line, index) => `BT /F1 10 Tf 40 ${790 - index * 14} Td (${pdfEscape(line)}) Tj ET`)
    .join("\n");
  const content = Buffer.from(text, "utf8");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content.toString("utf8")}\nendstream`,
  ];

  let offset = "%PDF-1.4\n".length;
  const body = objects
    .map((object, index) => {
      const entry = `${index + 1} 0 obj\n${object}\nendobj\n`;
      const currentOffset = offset;
      offset += Buffer.byteLength(entry);
      return { entry, offset: currentOffset };
    });

  const xrefStart = offset;
  const xref = [
    "xref",
    `0 ${objects.length + 1}`,
    "0000000000 65535 f ",
    ...body.map((object) => `${object.offset.toString().padStart(10, "0")} 00000 n `),
    "trailer",
    `<< /Size ${objects.length + 1} /Root 1 0 R >>`,
    "startxref",
    xrefStart.toString(),
    "%%EOF",
  ].join("\n");

  return Buffer.concat([
    Buffer.from("%PDF-1.4\n", "utf8"),
    ...body.map((object) => Buffer.from(object.entry, "utf8")),
    Buffer.from(xref, "utf8"),
  ]);
};

export const generateInvoicePdf = (invoice: PdfInvoice) => {
  const lines = [
    "TAX INVOICE",
    `Invoice: ${invoice.invoiceNo}`,
    `Date: ${formatDate(invoice.invoiceDate)}`,
    `Transaction: ${invoice.transaction.transactionNo}`,
    `Store: ${invoice.transaction.store.name} (${invoice.transaction.store.code})`,
    `Store GSTIN: ${invoice.transaction.store.gstin ?? invoice.gstin ?? "N/A"}`,
    `Place of Supply: ${invoice.placeOfSupply ?? invoice.transaction.store.state ?? "N/A"}`,
    `Customer: ${invoice.transaction.customer?.name ?? "Walk-in Customer"}`,
    `Customer GSTIN: ${invoice.transaction.customer?.gstin ?? "N/A"}`,
    "",
    "Items",
    ...invoice.transaction.items.flatMap((item, index) => [
      `${index + 1}. ${item.product.name} | SKU ${item.product.sku} | HSN ${item.product.hsnCode ?? "N/A"}`,
      `   Qty ${item.quantity} | Rate ${formatMoney(item.unitPrice)} | GST ${formatMoney(item.gstRate)}% | Total ${formatMoney(item.lineTotal)}`,
    ]),
    "",
    `Subtotal: ${formatMoney(invoice.subtotal)}`,
    `Taxable Amount: ${formatMoney(invoice.taxableAmount)}`,
    `CGST: ${formatMoney(invoice.cgstTotal)}`,
    `SGST: ${formatMoney(invoice.sgstTotal)}`,
    `IGST: ${formatMoney(invoice.igstTotal)}`,
    `Grand Total: ${formatMoney(invoice.grandTotal)}`,
    "",
    "Payments",
    ...invoice.payments.map(
      (payment) =>
        `${payment.method}: ${formatMoney(payment.amount)} ${payment.referenceNo ? `(${payment.referenceNo})` : ""}`
    ),
    "",
    "Generated by LIQO Retail ERP",
  ];

  return buildPdf(lines);
};

export const persistInvoicePdf = async (
  organizationId: string,
  invoiceNo: string,
  pdf: Buffer
) => {
  const directory = path.resolve(process.cwd(), "storage", "invoices", organizationId);
  await fs.mkdir(directory, { recursive: true });
  const fileName = `${invoiceNo.replace(/[^A-Z0-9-]/gi, "_")}.pdf`;
  const filePath = path.join(directory, fileName);
  await fs.writeFile(filePath, pdf);

  return filePath;
};
