apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liqo-ingress
spec:
  rules:
    - host: liqo-staging.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: liqo-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: liqo-frontend
                port:
                  number: 3000
