apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liqo-staging

resources:
  - ../../base
  - namespace.yaml

images:
  - name: ghcr.io/your-org/liqo-backend
    newName: ghcr.io/gauravdograa/liqo-backend
    newTag: latest
  - name: ghcr.io/your-org/liqo-frontend
    newName: ghcr.io/gauravdograa/liqo-frontend
    newTag: latest

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: ingress-patch.yaml
